version: "3.7"

services:
  goaventura:
    image: ejgallegos/goaventura:latest
    container_name: goaventura-container
    networks:
      - "traefik-net"
    restart: always
    ports:
      - "127.0.0.1:3003:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.goaventura.rule=Host(`goaventura.com.ar`)
      - traefik.http.routers.goaventura.tls=true
      - traefik.http.routers.goaventura.entrypoints=web,websecure
      - traefik.http.routers.goaventura.tls.certresolver=mytlschallenge
    env_file:
      - .env.production
    volumes:
      - goaventura-data:/app/public/data
    tmpfs:
      - /tmp:size=50m,mode=1777
      - /var/tmp:size=50m,mode=1777
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 768M
    read_only: true
    security_opt:
      - no-new-privileges:true

volumes:
  goaventura-data:
    driver: local

networks:
  traefik-net:
    external: true