version: "3.7"

services:
  goaventura:
    image: ejgallegos/goaventura:latest
    container_name: goaventura-container
    networks:
      - "traefik-net"
    restart: always
    ports:
      - "127.0.0.1:3003:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.goaventura.rule=Host(`goaventura.com.ar`)
      - traefik.http.routers.goaventura.tls=true
      - traefik.http.routers.goaventura.entrypoints=web,websecure
      - traefik.http.routers.goaventura.tls.certresolver=mytlschallenge
    env_file:
      - /root/goaventura/.env
    
networks:
  traefik-net:
    external: true